### ISSUE TITLE
first (dom0) command has an small error

### ISSUE THREAD

**Issue by TheGardner** [control-owl/suriGUI#1]
Hi Owl,

your first command of the dom0 commands have a small typo in there. Can you please correct?

...es-sys-ips/salt/sys-ips.top’ > /srv/salt/sys**.**ips.top

Beside this, it's working for me and does what it should. Nice idea, thanks mate!!!

Cheers Steffen

**Comment by control-owl** [comment]
Hi Steffen

Thx for reporting typo :+1: 
I will correct it.
